version: "3"
api:
  insecure: true
  dashboard: true
  debug: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
certificatesResolvers:
  anton-pizza:
    acme:
      email: anton.hagermalm@gmail.com
      storage: acme.json
      tlsChallenge: {}
