version: '3'
services:
  postgres:
    image: postgres:10.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mcoa_app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mcoa_dev
  mock_server:
    image: antonhager/mcoa_mock_server:1.0.0
    ports:
      - '1111:1111'
