version: 2.1

jobs:
  build-frontend:
    docker:
        - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dep-{{ checksum "frontend/package.json" }}
            - frontend-dep-
      - run: yarn --cwd frontend install
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-dep-{{ checksum "frontend/package.json" }}
      - run: yarn --cwd frontend run build
      - persist_to_workspace:
          root: frontend
          paths:
            - build

  deploy-frontend:
    docker:
        - image: circleci/node:10.15
    steps:
      - attach_workspace:
          at: build
      - run: 
          name: update build
          command: |
            mv build ${CIRCLE_BRANCH}-build
            scp -r -oStrictHostKeyChecking=no "${CIRCLE_BRANCH}-build" "ci@open.anton.pizza:/open.anton.pizza/builds"
      

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-frontend:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-frontend:
          requires:
            - build-frontend