version: 2.1

jobs:
  build-frontend:
    docker:
        - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dep-{{ checksum "frontend/package.json" }}
            - frontend-dep-
      - run: yarn --cwd frontend install
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-dep-{{ checksum "frontend/package.json" }}
      - run: yarn --cwd frontend run build
      - run: 
          name: update conf
          command: |
            if [ $CIRCLE_BRANCH == "master" ]; then
              export CONF_NAME=prod
            elif [ $CIRCLE_BRANCH == "staging" ]; then
              export CONF_NAME=staging
            fi
            mv frontend/build frontend/${CONF_NAME}-build
            scp -r -oStrictHostKeyChecking=no frontend/${CONF_NAME}-build "ci@open.anton.pizza:/open.anton.pizza/builds"
            scp nginx-conf/${CONF_NAME}-open.anton.pizza.conf "ci@open.anton.pizza:/open.anton.pizza/nginx-conf"
      - run: ssh -t "ci@open.anton.pizza" ls
      

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              only:
                - staging 
                - master