version: 2

jobs:
  build-frontend:
    docker:
        - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dep
      - run: yarn --cwd frontend install
      - save_cache:
          key: frontend-dep
          paths:
            - frontend/node_modules
      - run: yarn --cwd frontend run build
      - persist_to_workspace:
          root: frontend
          paths:
            - build

  deploy-frontend:
    docker:
        - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: build
      - run: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - run: mv build/build "${STAGE}:${CIRCLE_WORKFLOW_ID}"
      - run: gsutil cp -r "${STAGE}:${CIRCLE_WORKFLOW_ID}" "${BUCKET_URL}/${STAGE}"
      - run: scp -r -oStrictHostKeyChecking=no "./${STAGE}:${CIRCLE_WORKFLOW_ID}" "antonhagermalm@open.anton.pizza:/var/www/builds/${STAGE}"
      - run: ssh -oStrictHostKeyChecking=no "antonhagermalm@open.anton.pizza" "unlink /var/www/${STAGE}; ln -s /var/www/builds/${STAGE}/${STAGE}:${CIRCLE_WORKFLOW_ID} /var/www/${STAGE}"

  test-alohomora:
    docker:
        - image: circleci/node:10.15
          environment:
            NODE_ENV: "test"
        - image: antonhager/mcoa_mock_server
        - image: postgres:10.5
          environment:
            POSTGRES_USER: mcoa_app
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mcoa_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - alohomora-node-dep
      - run: yarn --cwd alohomora install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: yarn --cwd alohomora run test
      - save_cache:
          paths:
            - alohomora/node_modules
          key: alohomora-dep

  build-alohomora:
    docker:
        - image: circleci/node:10.15
          environment:
            NODE_ENV: "test"
        - image: antonhager/mcoa_mock_server
        - image: postgres:10.5
          environment:
            POSTGRES_USER: mcoa_app
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mcoa_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - alohomora-dep
      - setup_remote_docker
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - save_cache:
          paths:
            - alohomora/node_modules
          key: alohomora-dep
      - run: docker build -t ${DOCKER_USERNAME}/alohomora:${CIRCLE_WORKFLOW_ID} alohomora/ && docker push ${DOCKER_USERNAME}/alohomora:${CIRCLE_WORKFLOW_ID}

  deploy-alohomora:
    docker:
        - image: circleci/node:10.15
    steps:
      - run: ssh -oStrictHostKeyChecking=no "antonhagermalm@open.anton.pizza" "docker ps | grep "alohomora_$STAGE" && docker kill alohomora_$STAGE; docker ps -a | grep "alohomora_$STAGE" && docker rm alohomora_$STAGE; docker run --name alohomora_$STAGE --network swag --env-file /var/.envs/.$STAGE.env -d $DOCKER_USERNAME/alohomora:$CIRCLE_WORKFLOW_ID"

  build-mock-server:
    docker:
        - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t $DOCKER_USERNAME/mcoa_mock_server:${CIRCLE_WORKFLOW_ID} mock-server/ && docker push $DOCKER_USERNAME/mcoa_mock_server:${CIRCLE_WORKFLOW_ID}

  deploy-mock-server:
    docker:
        - image: circleci/node:10.15
    steps:
      - run: ssh -oStrictHostKeyChecking=no "antonhagermalm@open.anton.pizza" "docker ps | grep "mcoa_mock_server" && docker kill mcoa_mock_server; docker ps -a | grep "mcoa_mock_server" && docker rm mcoa_mock_server; docker run --name mcoa_mock_server --network swag -e PORT=80 -d $DOCKER_USERNAME/mcoa_mock_server:$CIRCLE_WORKFLOW_ID"

workflows:
  version: 2

  frontend-prod:
    jobs:
      - build-frontend:
          context: production
          filters:
            branches: 
              only: /master/
      - deploy-frontend:
          context: production
          requires:
            - build-frontend

  alohomora-prod:
    jobs: 
      - test-alohomora:
          context: production
          filters:
            branches: 
              only: /master/
      - build-alohomora:
          context: production
          requires:
            - test-alohomora
      - deploy-alohomora:
          context: production
          requires:
            - build-alohomora

  frontend-staging:
    jobs:
      - build-frontend:
          context: staging
          filters:
            branches: 
              only: /staging/
      - deploy-frontend:
          context: staging
          requires:
            - build-frontend

  alohomora-staging:
    jobs: 
      - test-alohomora:
          context: staging
          filters:
            branches: 
              only: /staging/
      - build-alohomora:
          context: staging
          requires:
            - test-alohomora
      - deploy-alohomora:
          context: staging
          requires:
            - build-alohomora
  
  mock-server:
    jobs:
      - build-mock-server:
          filters:
            branches: 
              only: /staging/
      - deploy-mock-server:
          requires:
            - build-mock-server
