version: 2

jobs:
  build-frontend:
    docker:
        - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dep
      - run: yarn --cwd frontend install
      - save_cache:
          key: frontend-dep
          paths:
            - frontend/node_modules
      - run: yarn --cwd frontend run build
      - persist_to_workspace:
          root: frontend
          paths:
            - build

  deploy-frontend:
    docker:
        - image: circleci/node:10.15
    steps:
      - attach_workspace:
          at: build
      - run: mv build "${CIRCLE_BRANCH}:${CIRCLE_WORKFLOW_ID}"
      - run: ls
      - run: scp -r -oStrictHostKeyChecking=no "./${CIRCLE_BRANCH}:${CIRCLE_WORKFLOW_ID}" "antonhagermalm@open.anton.pizza:/var/www/builds/${CIRCLE_BRANCH}"
      - run: ssh -oStrictHostKeyChecking=no "antonhagermalm@open.anton.pizza" "unlink /var/www/${CIRCLE_BRANCH}; ln -s /var/www/builds/${CIRCLE_BRANCH}/${CIRCLE_BRANCH}:${CIRCLE_WORKFLOW_ID} /var/www/${CIRCLE_BRANCH}"

  build-and-test-backend:
    docker:
        - image: circleci/node:10.15
          environment:
            NODE_ENV: "test"
        - image: antonhager/mcoa_mock_server
        - image: postgres:10.5
          environment:
            POSTGRES_USER: mcoa_app
            POSTGRES_PASSWORD: password
            POSTGRES_DB: make_chabo_open_again_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-node-dep-{{ checksum "backend-node/yarn.lock" }}
            - backend-node-dep
      - setup_remote_docker
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: yarn --cwd backend-node install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: yarn --cwd backend-node run test
      - save_cache:
          paths:
            - backend-node/node_modules
          key: backend-node-dep-{{ checksum "backend-node/yarn.lock" }}
      - run: docker build -t ${DOCKER_USERNAME}/mcoa_backend:${CIRCLE_WORKFLOW_ID} backend-node/ && docker push ${DOCKER_USERNAME}/mcoa_backend:${CIRCLE_WORKFLOW_ID}

  deploy-backend:
    docker:
        - image: circleci/node:10.15
    steps:
      - run: ssh -oStrictHostKeyChecking=no "antonhagermalm@open.anton.pizza" "docker ps | grep "mcoa_backend_$CIRCLE_BRANCH" && docker kill mcoa_backend_$CIRCLE_BRANCH; docker ps -a | grep "mcoa_backend_$CIRCLE_BRANCH" && docker rm mcoa_backend_$CIRCLE_BRANCH; docker run --name mcoa_backend_$CIRCLE_BRANCH --network swag --env-file /var/.envs/.$CIRCLE_BRANCH.env -d $DOCKER_USERNAME/mcoa_backend:$CIRCLE_WORKFLOW_ID"

  build-mock-server:
    docker:
        - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t $DOCKER_USERNAME/mcoa_mock_server:${CIRCLE_WORKFLOW_ID} mock-server/ && docker push $DOCKER_USERNAME/mcoa_mock_server:${CIRCLE_WORKFLOW_ID}

workflows:
  version: 2

  build-deploy-staging:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: staging
      - deploy-frontend:
          requires:
            - build-frontend
  
  frontend:
    jobs:
      - build-frontend:
          filters:
            branches: 
              only: /staging|master/
      - deploy-frontend:
          requires:
            - build-frontend
  backend:
    jobs: 
      - build-and-test-backend:
          filters:
            branches: 
              only: /staging|master/
      - deploy-backend:
          requires:
            - build-and-test-backend