version: 2
jobs:
  build-frontend:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dep-{{ checksum "frontend/package.json" }}
            - frontend-dep-
      - run: yarn --cwd frontend install
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-dep-{{ checksum "frontend/package.json" }}
      - run: yarn --cwd frontend run build
      - run: mv frontend/build frontend/${CIRCLE_BRANCH}-build
      - run: scp -r -oStrictHostKeyChecking=no frontend/${CIRCLE_BRANCH}-build "ci@open.anton.pizza:/open.anton.pizza/"
      - run: 
          name: update conf
          command: |
            if [ $CIRCLE_BRANCH == "master" ]; then
              export CONF_NAME=nginx-conf/prod-open.anton.pizza.conf
            else 
              export CONF_NAME=nginx-conf/staging-open.anton.pizza.conf
            fi
      - run: scp -r -oStrictHostKeyChecking=no $CONF_NAME "ci@open.anton.pizza:/open.anton.pizza/nginx-conf"
      - run: ssh -t "ci@open.anton.pizza:/open.anton.pizza/" ls
      

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              only:
                - staging