default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: makechaboopenagain
  username: default
  password: default
  host: localhost
  port: 5432

test:
  <<: *default
  database: backend-rails_test

production:
  <<: *default
  database: backend-rails_production
  username: backend-rails
  password: <%= ENV['BACKEND-RAILS_DATABASE_PASSWORD'] %>
