name: main_server
on:
  push:
    branches:
      - master
    paths:
      - server/
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build docker image
        run: docker build -t "antonhager/main_server:${{ github.sha }}" server
      - name: push docker image
        run: |
          echo ${{secrets.DOCKER_PASSWORD}} | docker login -u antonhager --password-stdin
          docker push "antonhager/main_server:${{ github.sha }}"
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: create ssh key
        run: |
          echo "${{secrets.SSH_KEY}}" > priv_key
          chmod 600 priv_key
      - name: deploy
        run: ssh -oStrictHostKeyChecking=no -i priv_key "antonhagermalm@open.anton.pizza" 'bash -s' < scripts/restart-main-server.sh ${{github.sha}}
      - name: clean old images
        run: ssh -oStrictHostKeyChecking=no -i priv_key "antonhagermalm@open.anton.pizza" 'bash -s' < scripts/remove-old-images.sh
